services:
  database:
    build: 
       context: ./database
    image: atsea_db
    environment:
      POSTGRES_USER: gordonuser
      POSTGRES_PASSWORD: gordonpass
      POSTGRES_DB: atsea
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432" 
    networks:
      - back-tier

  appserver:
    build:
       context: app
       dockerfile: Dockerfile-dev
    image: atsea_app
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - database
    networks:
      - front-tier
      - back-tier
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/atsea
      SPRING_DATASOURCE_USERNAME: gordonuser
      SPRING_DATASOURCE_PASSWORD: gordonpass
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

networks:
  front-tier:
  back-tier: